---
version: "3.7"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    expose:
      - 2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  msd-kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    expose:
      - 9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://msd-kafka:29092,PLAINTEXT_HOST://msd-kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  msd-etcd:
    image: quay.io/coreos/etcd
    expose:
      - 2379
    command:
      - /usr/local/bin/etcd
      - -name
      - msd-etcd
      - -advertise-client-urls
      - http://msd-etcd:2379
      - -listen-client-urls
      - http://0.0.0.0:2379
  datagenerator:
    image: gcr.io/msdclustering/datagenerator
    depends_on: 
      - msd-kafka
      - zookeeper
      - msd-etcd
  p2ccprocessor:
    image: gcr.io/msdclustering/p2ccprocessor
    depends_on: 
      - msd-kafka
      - zookeeper
      - msd-etcd
  cc2cprocessor:
    image: gcr.io/msdclustering/cc2cprocessor
    depends_on: 
      - msd-kafka
      - zookeeper
      - msd-etcd
  webserver:
    image: gcr.io/msdclustering/webserver
    depends_on: 
      - msd-kafka
      - zookeeper
      - msd-etcd
    ports:
      - 5656:5656


